# frozen_string_literal: true

source 'https://rubygems.org'

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

gem 'curb', '~> 0.9.10'
gem 'nokogiri', '~> 1.13'

group :development do
  gem 'pry', '~> 0.12.2'
end
